Online_Shop/Areas/Admin/Controllers/ProductController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Online_Shop.Data;
using Online_Shop.Models;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Online_Shop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]

    public class ProductController : Controller
    {
        private ApplicationDbContext _db;
        private IHostingEnvironment _he;
        public ProductController(ApplicationDbContext db,IHostingEnvironment he)
        {
            _db = db;
            _he = he;
        }
        
        public IActionResult Index()
        {
            return View(_db.products.Include(c=>c.ProductTypes).Include(c=>c.specialTag).ToList());
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Index(decimal? lowAmount,decimal? largeAmount )
        {
            var Products = _db.products.Include(c => c.ProductTypes).Include(c => c.specialTag).Where(c => c.Price >= largeAmount && c.Price <= largeAmount).ToList();
            if(largeAmount==null || largeAmount == null)
            {
            Products = _db.products.Include(c => c.ProductTypes).Include(c => c.specialTag).ToList();
            }

            return View(Products);



        }

        public IActionResult Create()

        {
            ViewData["productTypeId"] = new SelectList(_db.productTypes.ToList(), "Id", "Producttype");
            ViewData["TagId"] = new SelectList(_db.specialTags.ToList(), "Id", "specialTageName");

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
       

        public async Task<IActionResult> Create(Products products,IFormFile image)
        {
            if (ModelState.IsValid)

            {
                var SarchProduct = _db.products.FirstOrDefault(c => c.Name == products.Name);
                if (SarchProduct!=null)
                {
                    ViewBag.message = "This Product Is already exits";
                    ViewData["productTypeId"] = new SelectList(_db.productTypes.ToList(), "Id", "Producttype");
                    ViewData["TagId"] = new SelectList(_db.specialTags.ToList(), "Id", "specialTageName");

                    return View(products);
                }

                if (image != null)
                {
                    var name=Path.Combine(_he.WebRootPath+"/Images",Path.GetFileName(image.FileName));  
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    products.Image = "Images/" + image.FileName;
                }
                if (image == null)
                {
                     
                    products.Image = "Images/noimage.PNG"; 

                }
                _db.products.Add(products);
                await _db.SaveChangesAsync();
                return RedirectToAction(actionName:nameof(Index));

            }
            return View(products);
        }





        //GET Edit Action Method//
        public ActionResult Edit(int? id)
        {

            ViewData["productTypeId"] = new SelectList(_db.productTypes.ToList(), "Id", "Producttype");
            ViewData["TagId"] = new SelectList(_db.specialTags.ToList(), "Id", "specialTageName");
            if (id == null)
            {
                return NotFound();
            }
            var products = _db.products.Include(c => c.ProductTypes).Include(c => c.specialTag).FirstOrDefault(c => c.Id == id);
            if (products == null)
            {
                return NotFound();

            }
            return View(products);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Products products, IFormFile image)
        {
            if (ModelState.IsValid)
            {
                var SarchProduct = _db.products.FirstOrDefault(c => c.Name == products.Name);

                if (SarchProduct!=null)
                {
                    ViewBag.message = "This Product Is already exits";
                    ViewData["productTypeId"] = new SelectList(_db.productTypes.ToList(), "Id", "Producttype");
                    ViewData["TagId"] = new SelectList(_db.specialTags.ToList(), "Id", "specialTageName");

                    return View(products);

                }

                if (image != null)
                {
                    var name = Path.Combine(_he.WebRootPath + "/Images", Path.GetFileName(image.FileName));
                    await image.CopyToAsync(new FileStream(name, FileMode.Create));
                    products.Image = "Images/" + image.FileName;
                }
                if (image == null)
                {

                    products.Image = "Images/noimage.PNG";

                }
                _db.products.Update(products);
                await _db.SaveChangesAsync();
                return RedirectToAction(actionName: nameof(Index));

            }
            return View(products);


        }
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var Products = _db.products.Include(c => c.ProductTypes).Include(c => c.specialTag).FirstOrDefault(c => c.Id == id);
            if (Products==null)
            {
                return NotFound();
            }

            return View(Products);
        }

        //Delect Action//
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var Product = _db.products.Include(c=>c.specialTag).Include(c=>c.ProductTypes).Where(c => c.Id == id).FirstOrDefault();
            if (Product == null)
            {
                return NotFound();
            }

            return View(Product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirm(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = _db.products.FirstOrDefault(c => c.Id == id);
            if (product == null)
            {
                return NotFound();
            }
            _db.products.Remove(product);
            await _db.SaveChangesAsync();
            

            return RedirectToAction(actionName: nameof(Index));
        }
    }
}

Online_Shop/Areas/Admin/Controllers/ProductTypeController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Online_Shop.Data;
using Online_Shop.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Online_Shop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class ProductTypeController : Controller
    {
        private ApplicationDbContext _db;
        public ProductTypeController(ApplicationDbContext db)
        {
            _db = db;
        }
        //[AllowAnonymous]
        
        public IActionResult Index()
        {
            return View(_db.productTypes.ToList());
        }
      
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductType product)
        {
            if (ModelState.IsValid)
            {
                _db.productTypes.Add(product);
                await _db.SaveChangesAsync();
                TempData["Save"] = "Product Type Has Been Saved!";
                return RedirectToAction(actionName:nameof(Index));


            }
            return View(product);
        }
        
        public ActionResult Edit(int ? id)
        {
            var ProductType = _db.productTypes.Find(id);
            if (id == null)
            {
                return NotFound();

            }
           
            return View(ProductType);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductType product)
        {
            if (ModelState.IsValid)
            {
                _db.Update(product);
                await _db.SaveChangesAsync();
                TempData["Update"] = "Product Type Has Been Update Successful ";
                return RedirectToAction(actionName: nameof(Index));


            }
            return View(product);
        }
        

        public ActionResult Details(int? id)
        {
            var ProductType = _db.productTypes.Find(id);
            if (id == null)
            {
                return NotFound();

            }

            return View(ProductType);
        }

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public  IActionResult Details(ProductType product)
        //{

        //    return  RedirectToAction(actionName: nameof(Index));
        //}

        
        public ActionResult Delete(int? id)
        {
            var ProductType = _db.productTypes.Find(id);
            if (id == null)
            {
                return NotFound();

            }

            return View(ProductType);
        }
        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id, ProductType product)
        {
            if (id == null)
            {
                return NotFound();

            }
            if (id!= product.Id)
            {
                return NotFound();

            }
            var productType = _db.productTypes.Find(id);
            if(productType == null)
            {
                return NotFound();

            }
            if (ModelState.IsValid)
            {
                _db.Remove(productType);
                await _db.SaveChangesAsync();
                TempData["Delete"] = "Product Type Has Been Delete Successful ";
                return RedirectToAction(actionName: nameof(Index));


            }
            return View(product);
        }

        
    }
}

Online_Shop/Areas/Admin/Controllers/SpecialTagController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Online_Shop.Data;
using Online_Shop.Models;
using System.Linq;
using System.Threading.Tasks;

namespace Online_Shop.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize]
    public class SpecialTagController : Controller
    {
        private ApplicationDbContext _db;
        public SpecialTagController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            return View(_db.specialTags.ToList());
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(specialTag product)
        {
            if (ModelState.IsValid)
            { 
                 _db.specialTags.Add(product);
                 await _db.SaveChangesAsync();
                TempData["Save"] = "Product Type Has Been Saved!";
                return RedirectToAction(actionName:nameof(Index));

            }
            return View(product);
        }
        public IActionResult Edit( int? id)
        {
            var specialTag = _db.specialTags.Find(id);
            if(specialTag == null)
            {
                return NotFound();
            }
            return View(specialTag);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(specialTag product)
        {
            if (ModelState.IsValid)
            {
                _db.specialTags.Update(product);
                await _db.SaveChangesAsync();
                TempData["Update"] = "Product Type Has Been Update Successful ";
                return RedirectToAction(actionName: nameof(Index));

            }
            return View(product);
        }

        public IActionResult Details(int? id)
        {
            var Specialtg= _db.specialTags.Find(id);
            if(Specialtg == null)
            {
                return NotFound();
            }
            return View(Specialtg);
        }
        public IActionResult Delete ( int? id)
        {
            var specialTag = _db.specialTags.Find(id);
            if(specialTag == null)
            {
                return NotFound();
            }
            return View(specialTag);
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(int? id,specialTag product)
            
        {
            if (id == null)
            {
                return NotFound();

            }
            if (id != product.Id)
            {
                return NotFound();


            }

            if (ModelState.IsValid)
            {
                _db.specialTags.Remove(product);
                await _db.SaveChangesAsync();
                TempData["Delete"] = "Product Type Has Been Delete Successful ";
                return RedirectToAction(actionName: nameof(Index));

            }
            return View(product);
        }


    }
}

Online_Shop/Views/Shared/_ButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit"  class="btn btn-primary" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a asp-action="Details"  class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list-ul"></i></a>
        <a asp-action="Delete"  class="btn btn-danger" asp-route-id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

Online_Shop/Views/Shared/_Layout.cshtml
@using System.Net.Http
@using Online_Shop.Utility
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor
@{
    var userRole = HttpContextAccessor.HttpContext.Session.GetString(key: "roleName");
    int Count = 0;
    List<Products> products = HttpContextAccessor.HttpContext.Session.Get<List<Products>>("products");
    if (products == null)
    {
        products = new List<Products>();
    }
    Count = products.Count();
}

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Online_Shop</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link href="~/FontAwosem/css/all.css" rel="stylesheet" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.13.1/build/css/alertify.min.css" />
    <link rel="stylesheet" herf="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="/DataTables/datatables.css">
    <link rel="stylesheet" href="//cdn.jsdelivr.net/npm/alertifyjs@1.11.2/build/css/alertify.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/buttons/1.5.6/css/buttons.dataTables.min.css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">


    <link rel="stylesheet" href="~/css/site.css" />
    <style>
        .error {
            color: red;
        }
    </style>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="Customer" asp-controller="Home" asp-action="Index">OnlineShop</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        @if (userRole == "Super User")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductType" asp-action="Index">Product Type </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialTag" asp-action="Index">Tag Name  </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                            </li>

                        }
                        else if (userRole == "Admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="ProductType" asp-action="Index">Product Type </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="SpecialTag" asp-action="Index">Tag Name  </a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                            </li>
                        }


                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Customer" asp-controller="Home" asp-action="Cart">
                                <i class="fa-solid fa-cart-plus"></i>
                                (@Count)
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Online_Shop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
        <script src="~/FontAwosem/js/all.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>


    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" charset="utf8" src="/DataTables/datatables.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/pdfmake.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.53/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.5.6/js/buttons.print.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>


    @RenderSection("Scripts", required: false)
</body>
</html>

Online_Shop/Views/Shared/_PartialView.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
﻿

<div class="btn-group">
    <a asp-action="Edit" class="btn btn-primary" asp-route-id="@Model">
        <i class="far fa-edit"></i>
    </a>
    <a asp-action="Details" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list-ul"></i></a>
    <a asp-action="Lockout" class="btn btn-danger" asp-route-id="@Model">
        <i class="fas fa-trash-alt"></i>
    </a>
</div>

Online_Shop/Views/Shared/_ProductsPageButtonPartial .cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="Product" class="btn btn-primary" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a asp-action="Details" asp-controller="Product" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list-ul"></i></a>
        <a asp-action="Delete" asp-controller="Product" class="btn btn-danger" asp-route-id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>

Online_Shop/Views/Shared/_TagPageButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td style="width: 150px">
    <div class="btn-group">
        <a asp-action="Edit" asp-controller="SpecialTag" class="btn btn-primary" asp-route-id="@Model">
            <i class="far fa-edit"></i>
        </a>
        <a asp-action="Details" asp-controller="SpecialTag" class="btn btn-success" asp-route-id="@Model"><i class="fas fa-list-ul"></i></a>
        <a asp-action="Delete" asp-controller="SpecialTag" class="btn btn-danger" asp-route-id="@Model">
            <i class="fas fa-trash-alt"></i>
        </a>
    </div>
</td>